var routeConfig = {};

import _AccountManagement from './pages/AccountManagement';
import _Demo from './pages/Demo';
import _Index from './pages/Index';
import _InventoryCarDetail_component_CarInfo from './pages/InventoryCarDetail/component/CarInfo';
import _InventoryCarDetail_component_CarTag from './pages/InventoryCarDetail/component/CarTag';
import _InventoryCarDetail_component from './pages/InventoryCarDetail/component';
import _InventoryCarDetail_component_style from './pages/InventoryCarDetail/component/style';
import _InventoryCarDetail from './pages/InventoryCarDetail';
import _InventoryCarList_Component_ColorAndTypeSelector from './pages/InventoryCarList/Component/ColorAndTypeSelector';
import _InventoryCarList_Component_FormatFilterData from './pages/InventoryCarList/Component/FormatFilterData';
import _InventoryCarList_Component from './pages/InventoryCarList/Component';
import _InventoryCarList_Component_listItem from './pages/InventoryCarList/Component/listItem';
import _InventoryCarList_Component_Styles from './pages/InventoryCarList/Component/Styles';
import _InventoryCarList_Component_TagList from './pages/InventoryCarList/Component/TagList';
import _InventoryCarList from './pages/InventoryCarList';
import _InventoryHome from './pages/InventoryHome';
import _InventoryHome_SearchPageDemo from './pages/InventoryHome/SearchPageDemo';
import _InventoryKanBan_component_inputResult from './pages/InventoryKanBan/component/inputResult';
import _InventoryKanBan_component_Search from './pages/InventoryKanBan/component/Search';
import _InventoryKanBan_component_selectResult from './pages/InventoryKanBan/component/selectResult';
import _InventoryKanBan from './pages/InventoryKanBan';
import _InventorySharing_component_SearchList from './pages/InventorySharing/component/SearchList';
import _InventorySharing_component_SearchResult from './pages/InventorySharing/component/SearchResult';
import _InventorySharing from './pages/InventorySharing';
import _InventoryVendibility from './pages/InventoryVendibility';
import _List from './pages/List';
import _stockCarList from './pages/stockCarList';
import _stockCarListIteration_component_Search from './pages/stockCarListIteration/component/Search';
import _stockCarListIteration from './pages/stockCarListIteration';
import _stockControl from './pages/stockControl';
import _stockStructure_component_Search from './pages/stockStructure/component/Search';
import _stockStructure from './pages/stockStructure';
import _stockStructure_index11 from './pages/stockStructure/index11';
import _stockStructure_kanban from './pages/stockStructure/kanban';

routeConfig['/AccountManagement'] = _AccountManagement;
routeConfig['/Demo'] = _Demo;
routeConfig['/Index'] = _Index;
routeConfig['/InventoryCarDetail/component/CarInfo'] = _InventoryCarDetail_component_CarInfo;
routeConfig['/InventoryCarDetail/component/CarTag'] = _InventoryCarDetail_component_CarTag;
routeConfig['/InventoryCarDetail/component'] = _InventoryCarDetail_component;
routeConfig['/InventoryCarDetail/component/style'] = _InventoryCarDetail_component_style;
routeConfig['/InventoryCarDetail'] = _InventoryCarDetail;
routeConfig['/InventoryCarList/Component/ColorAndTypeSelector'] = _InventoryCarList_Component_ColorAndTypeSelector;
routeConfig['/InventoryCarList/Component/FormatFilterData'] = _InventoryCarList_Component_FormatFilterData;
routeConfig['/InventoryCarList/Component'] = _InventoryCarList_Component;
routeConfig['/InventoryCarList/Component/listItem'] = _InventoryCarList_Component_listItem;
routeConfig['/InventoryCarList/Component/Styles'] = _InventoryCarList_Component_Styles;
routeConfig['/InventoryCarList/Component/TagList'] = _InventoryCarList_Component_TagList;
routeConfig['/InventoryCarList'] = _InventoryCarList;
routeConfig['/InventoryHome'] = _InventoryHome;
routeConfig['/InventoryHome/SearchPageDemo'] = _InventoryHome_SearchPageDemo;
routeConfig['/InventoryKanBan/component/inputResult'] = _InventoryKanBan_component_inputResult;
routeConfig['/InventoryKanBan/component/Search'] = _InventoryKanBan_component_Search;
routeConfig['/InventoryKanBan/component/selectResult'] = _InventoryKanBan_component_selectResult;
routeConfig['/InventoryKanBan'] = _InventoryKanBan;
routeConfig['/InventorySharing/component/SearchList'] = _InventorySharing_component_SearchList;
routeConfig['/InventorySharing/component/SearchResult'] = _InventorySharing_component_SearchResult;
routeConfig['/InventorySharing'] = _InventorySharing;
routeConfig['/InventoryVendibility'] = _InventoryVendibility;
routeConfig['/List'] = _List;
routeConfig['/stockCarList'] = _stockCarList;
routeConfig['/stockCarListIteration/component/Search'] = _stockCarListIteration_component_Search;
routeConfig['/stockCarListIteration'] = _stockCarListIteration;
routeConfig['/stockControl'] = _stockControl;
routeConfig['/stockStructure/component/Search'] = _stockStructure_component_Search;
routeConfig['/stockStructure'] = _stockStructure;
routeConfig['/stockStructure/index11'] = _stockStructure_index11;
routeConfig['/stockStructure/kanban'] = _stockStructure_kanban;

export default routeConfig;